# Generated by Django 4.0.4 on 2022-06-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color_code',
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tag')),
            ],
            options={
                'db_table': 'reviewtags',
            },
        ),
    ]
