# Generated by Django 4.0.4 on 2022-06-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('reviews', '0002_remove_review_tag_remove_tag_color_code_reviewtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageReview',
            new_name='ReviewImage',
        ),
        migrations.RenameField(
            model_name='reviewtag',
            old_name='Review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewtag',
            old_name='Tag',
            new_name='tag',
        ),
        migrations.AlterModelTable(
            name='reviewimage',
            table='review_images',
        ),
    ]
