# Generated by Django 4.0.4 on 2022-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_thumbnailimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=200),
        ),
    ]
