# Generated by Django 4.0.4 on 2022-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='en_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
