# Generated by Django 4.0.4 on 2022-10-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
    ]
