# Generated by Django 4.0.4 on 2022-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_job_actor_birth_actor_debut_actor_debut_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='agency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
